spring:
  profiles:
    active:
      - dev
---
server:
  port: 8081

spring:
  profiles: dev
  application:
    name: notebusiness-app
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/net_note?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: root # 数据库连接密码
  security:
    user:
      name: admin  # 认证用户名
      password: netnote  # 认证密码
#      roles:
#       - USER # 授权角色

mybatis:
  mapper-locations: # 所有的mapper映射文件
    - classpath:mappers/*.xml
  type-aliases-package: com.netnote.common.model
eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://admin:netnote@eureka1:7001/eureka # ,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance:
    instance-id: notebusiness-instance-1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 600  # 如果现在超过了n秒的间隔（默认是90秒）

ribbon:
  eureka:
    enabled: true

info:
  app.name: notebusiness-info
  company.name: netnote
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

logging:
  level:
    com.netnote.business: debug

#自定义参数
snowflake4idworker:
  workerId: 1
  datacenterId: 1
  sequence: 1

##########################################
