spring:
  profiles:
    active:
      - dev
---
server:
  port: 8081



spring:
  profiles: dev
  application:
    name: notebusiness-app
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/net_note?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: root # 数据库连接密码
  zipkin:
    base-url: http://localhost:8601  #所有追踪用到的数据提交到这个服务
    sender:
      type: rabbit   #提交的类型是web服务
  sleuth:
    sampler:
      probability: 1.0 #定义采样比率，默认0.1
  cloud:
    stream:
      rabbit:
        bindings:
          hxf-input:
            consumer:
              bindingRoutingKey: hxfRoutingKey
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                addresses: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings: # 服务的整合处理
        hxf-input: # 这个名字是一个通道的名称，可以自定义
          destination: NetNoteExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: hxf-group #对于生产者发出的消息，相同组下的消费者，只能有一个能成功消费


mybatis:
  mapper-locations: # 所有的mapper映射文件
    - classpath:mappers/*.xml


eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://admin:netnote@eureka1:7001/eureka # ,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance:
    instance-id: notebusiness-instance-1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 600  # 如果现在超过了n秒的间隔（默认是90秒）

ribbon:
  eureka:
    enabled: true

info:
  app.name: notebusiness-info
  company.name: netnote
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

logging:
  level:
    com.netnote.business: debug

#自定义参数
snowflake4idworker:
  workerId: 1
  datacenterId: 1
  sequence: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'
##########################################
